backend:
  name: github
  repo: Clayworkscoop/clayworks

media_folder: "images"

collections:
  - label: "Website settings"
    name: "website-settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Location"
            name: "location"
            widget: "object"
            fields:
              - label: "Street address"
                name: "street_address"
                widget: "string"
              - label: "Locality"
                name: "locality"
                widget: "string"
              - label: "Region"
                name: "region"
                widget: "string"
              - label: "Country"
                name: "country"
                widget: "string"
              - label: "Postal Code"
                name: "postalCode"
                widget: "string"
          - label: "email"
            name: "email"
            widget: "string"

# ------- home page ----------

  - label: "Pages"
    name: "pages"
    files:
      - label: "Home page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
              - label: "Button Link"
                name: "buttonLink"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"

          - label: "About the Studio"
            name: "about-coop"
            widget: "object"
            fields:
              - label: "Title 1"
                name: "title-1"
                widget: "string"
              - label: "Text part 1"
                name: "text-1"
                widget: "string"
              - label: "Image 1"
                name: "image_1"
                widget: "image"
              - label: "Title 2"
                name: "title-2"
                widget: "string"
              - label: "Text part 2"
                name: "text-2"
                widget: "string"
              - label: "Image 2"
                name: "image_2"
                widget: "image"

          - label: "Studio Features"
            name: "features"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Image"
                name: "image_1"
                widget: "image"

          - label: "Studio's Gallery"
            name: "gallery"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Image"
                name: "image_1"
                widget: "image"

          - label: "What's happening at the Studio"
            name: "happenings"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Card 1 link"
                name: "card_1_link"
                widget: "string"
              - label: "Card 2 link"
                name: "card_2_link"
                widget: "string"

          - label: "Newsletter section"
            name: "newsletter"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Subtitle"
                name: "subtitle"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
              - label: "Email to receive the newsletter requests"
                name: "email-to"
                widget: "string"

          - label: "Apply for membership section"
            name: "membership"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Subtitle"
                name: "subtitle"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
              - label: "Url to the application form"
                name: "formLink"
                widget: "string"

# ------- end of home page ----------
# -------  event page ----------

      - label: "Events page"
        name: "events"
        file: "_data/events.yml"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
              - label: "Button Link"
                name: "buttonLink"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"

          - label: "Upcoming event"
            name: "upcoming"
            widget: "object"
            fields:
              - label: "Section Title"
                name: "sectionTitle"
                widget: "string"
              - label: "Event title"
                name: "title"
                widget: "string"
              - label: "Event date"
                name: "date"
                widget: "string"
              - label: "Event time"
                name: "time"
                widget: "string"
              - label: "Event price"
                name: "price"
                widget: "string"
              - label: "Event description"
                name: "description"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Image Description"
                name: "imageAlt"
                widget: "string"
              - label: "Additional link text"
                name: "linkText"
                widget: "string"
              - label: "Additional link"
                name: "link"
                widget: "string"

          - label: "Future events"
            name: "next"
            widget: "object"
            fields:
              - label: "Section Title"
                name: "sectionTitle"
                widget: "string"
              - label: "Event 1 title"
                name: "card-1-title"
                widget: "string"
              - label: "Event 1 date"
                name: "card-1-date"
                widget: "string"
              - label: "Event 1 time"
                name: "card-1-time"
                widget: "string"
              - label: "Event 1 price"
                name: "card-1-price"
                widget: "string"
              - label: "Event 1 description"
                name: "card-1-description"
                widget: "string"
              - label: "Event 1 image"
                name: "card-1-image"
                widget: "image"
              - label: "Image Description"
                name: "card-1-imageAlt"
                widget: "string"
              - label: "Additional link text"
                name: "linkText-1"
                widget: "string"
              - label: "Additional link"
                name: "link-1"
                widget: "string"

              - label: "Event 2 title"
                name: "card-2-title"
                widget: "string"
              - label: "Event 2 date"
                name: "card-2-date"
                widget: "string"
              - label: "Event 2 time"
                name: "card-2-time"
                widget: "string"
              - label: "Event 2 price"
                name: "card-2-price"
                widget: "string"
              - label: "Event 2 description"
                name: "card-2-description"
                widget: "string"
              - label: "Event 2 image"
                name: "card-2-image"
                widget: "image"
              - label: "Image Description"
                name: "card-2-imageAlt"
                widget: "string"
              - label: "Additional link text"
                name: "linkText-2"
                widget: "string"
              - label: "Additional link"
                name: "link-2"
                widget: "string"


# ------- end of events page ----------
# -------  classes page ----------

      - label: "Classes page"
        name: "classes"
        file: "_data/classes.yml"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
              - label: "Button Link"
                name: "buttonLink"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"

          - label: "Upcoming class"
            name: "upcoming"
            widget: "object"
            fields:
              - label: "Section Title"
                name: "sectionTitle"
                widget: "string"
              - label: "Class title"
                name: "title"
                widget: "string"
              - label: "Teacher"
                name: "instructor"
                widget: "string"
              - label: "Dates"
                name: "date"
                widget: "string"
              - label: "Week days"
                name: "days"
                widget: "string"
              - label: "Class time"
                name: "time"
                widget: "string"
              - label: "Class price"
                name: "price"
                widget: "string"
              - label: "Students level"
                name: "level"
                widget: "string"
              - label: "Register Button"
                name: "registerButton"
                widget: "string"
              - label: "Button Link"
                name: "registerLink"
                widget: "string"
              - label: "Description header"
                name: "descriptionTitle"
              - label: "Class description"
                name: "description"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Image Description"
                name: "imageAlt"
                widget: "string"
              - label: "email"
                name: "email"
                widget: "string"

          - label: "Future classes"
            name: "next"
            widget: "object"
            fields:
              - label: "Section Title"
                name: "sectionTitle"
                widget: "string"
              - label: "Class 1 title"
                name: "card-1-title"
                widget: "string"
              - label: "Teacher"
                name: "card-1-instructor"
                widget: "string"
              - label: "Dates"
                name: "card-1-date"
                widget: "string"
              - label: "week days"
                name: "card-1-days"
                widget: "string"
              - label: "Class time"
                name: "card-1-time"
                widget: "string"
              - label: "Class price"
                name: "card-1-price"
                widget: "string"
              - label: "Students level"
                name: "card-1-level"
                widget: "string"
              - label: "Register Button"
                name: "card-1-registerButton"
                widget: "string"
              - label: "Button Link"
                name: "card-1-registerLink"
                widget: "string"
              - label: "Description header"
                name: "card-1-descriptionTitle"
              - label: "Class description"
                name: "card-1-description"
                widget: "string"
              - label: "Image"
                name: "card-1-image"
                widget: "image"
              - label: "Image Description"
                name: "card-1-imageAlt"
                widget: "string"
              - label: "email"
                name: "email-1"
                widget: "string"
              - label: "Class 2 title"
                name: "card-2-title"
                widget: "string"
              - label: "Teacher"
                name: "card-2-instructor"
                widget: "string"
              - label: "Dates"
                name: "card-2-date"
                widget: "string"
              - label: "week days"
                name: "card-2-days"
                widget: "string"
              - label: "Class time"
                name: "card-2-time"
                widget: "string"
              - label: "Class price"
                name: "card-2-price"
                widget: "string"
              - label: "Students level"
                name: "card-2-level"
                widget: "string"
              - label: "Register Button"
                name: "card-2-registerButton"
                widget: "string"
              - label: "Button Link"
                name: "card-2-registerLink"
                widget: "string"
              - label: "Description header"
                name: "card-2-descriptionTitle"
              - label: "Class description"
                name: "card-2-description"
                widget: "string"
              - label: "Image"
                name: "card-2-image"
                widget: "image"
              - label: "Image Description"
                name: "card-2-imageAlt"
                widget: "string"
              - label: "email"
                name: "email-2"
                widget: "string"


# ------- end of classes page ----------
# -------  artists page ----------

      - label: "Artists page"
        name: "artists"
        file: "_data/artists.yml"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"

# ------- end of artists page ----------
# -------  artist profile page ----------

      - label: "Artists page"
        name: "artists"
        file: "_data/artists.yml"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"

      - label: "About page"
        name: "about"
        file: "about.md"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "desc"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"

  - label: "Artists profiles"
    name: "artists"
    folder: "_artists"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "artists-profile"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Artist picture"
        name: "artistImage"
        widget: "image"
      - label: "Name for Artist picture"
        name: "artistImage_alt"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Gallery Title"
        name: "galleryTitle"
        widget: "string"
      - label: "Gallery Description"
        name: "galleryDescription"
        widget: "string"
      - label: "Artwork 1 image"
        name: "artImage_1"
        widget: "image"
      - label: "Artwork 1 image short description"
        name: "artImage_1_alt"
        widget: "string"
      - label: "Artwork 2 image"
        name: "artImage_2"
        widget: "image"
      - label: "Artwork 3 image short description"
        name: "artImage_3_alt"
        widget: "string"
      - label: "Artwork 4 image"
        name: "artImage_4"
        widget: "image"
      - label: "Artwork 5 image short description"
        name: "artImage_5_alt"
        widget: "string"
      - label: "Artwork 6 image"
        name: "artImage_6"
        widget: "image"
      - label: "Artwork 7 image short description"
        name: "artImage_7_alt"
        widget: "string"
      - label: "Artwork 8 image short description"
        name: "artImage_8_alt"
        widget: "string"
      - label: "Contact Artist section title"
        name: "contactArtist_title"
        widget: "string"
      - label: "Button text"
        name: "contactArtist"
        widget: "string"
      - label: "Artist's email"
        name: "contactArtist_email"
        widget: "string"
